### PR TITLE
Add more points to Other Non-functional Requirements

### PR DESCRIPTION
**Pull request by iamsebinsunny**
Add more points to Other Non-functional Requirements

### CODE REVIEW

**Review by srinair7 — CHANGES_REQUESTED** [review]
not enough points. add more

**Review by srinair7 — CHANGES_REQUESTED** [review]
1-2 points are not enough.. neeed wayyy more

**Comment by iamsebinsunny** [comment]
> 1-2 points are not enough.. neeed wayyy more

@srinair7 we have total 4-5  distinct points which are covering the topic, are we expecting more ?

**Review by srinair7 — APPROVED** [review]
LGTM! Approving for the same

**Pull request merged**
